### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by panicbit** [panicbit/rust-rcon#19]

**Comment by jenrik** [comment]
Remember to test that you examples at least can build

**Comment by panicbit** [comment]
IIRC "cargo test" should cover this, although, I think I'd have to pass "--all".

**Comment by panicbit** [comment]
Well, it turns out I actually did set up CI already... like, 5 years ago:
![grafik](https://user-images.githubusercontent.com/628445/125166141-80f9cd80-e19a-11eb-9791-a9d9383a0a89.png)

The repo was still managed by `travis-ci.org`, but I have migrated it to `travis-ci.com` now.
However, for some reason travis does not see new pull requests. :disappointed:

**Comment by panicbit** [comment]
Ok, so I found out that the builds on travis are getting rejected with "Could not authorize build requested".
The [travis docs](https://docs.travis-ci.com/user/common-build-problems/#i-pushed-a-commit-and-cant-find-its-corresponding-build) say this:

> “Could not authorize build request”, usually means that the account’s subscription expired or that it ran out of trial builds.

Looks like I'll have to look into other CI providers then.
**Hello GitHub Actions‽**

**Comment by panicbit** [comment]
I've set up GitHub Actions with a couple of clicks now :man_shrugging:.
Seems to work fine https://github.com/panicbit/rust-rcon/actions
