### ISSUE TITLE
Limit size of sent packages

### ISSUE THREAD

**Issue by klemens** [panicbit/rust-rcon#5]
The maximum allowed packet size seems to be 1428 bytes, which is a payload of 1414 bytes excluding headers and null-terminating bytes. If 1429 bytes or more are sent, the server immediately closes the connection. (*Edit*: this was tested using Minecraft 1.7.10)

This should probably be rejected in the client right away by returning a `PacketTooLarge` error from `cmd()`, whose return type would need to be changed to `RconResult<String>` (or we could add a new function `executeCommand` or similar and deprecate `cmd`).

I can submit a PR if you like.

**Comment by panicbit** [comment]
IIRC there was a way to split a command into multiple packages and cmd()
should do that. In any case I think the return types should be changed to
RconResult and RconResult should be renamed to Result.

Klemens Schölhorn <notifications@github.com> schrieb am Do., 3. Nov. 2016,
19:13:

**Comment by klemens** [comment]
I did a little bit of googling, but could not find a way to split packets. Also testing did not reveal anything useful. The server executes a command as soon as the first packet is received.

Do you have any pointers?

> RconResult should be renamed to Result

I agree.

**Comment by panicbit** [comment]
Looks like I was thinking of multipacket responses
https://developer.valvesoftware.com/wiki/Source_RCON_Protocol#Multiple-packet_Responses
.
So I guess we should introduce an error for too long cmds.

Klemens Schölhorn <notifications@github.com> schrieb am Do., 3. Nov. 2016,
19:24:

**Comment by klemens** [comment]
> Looks like I was thinking of multipacket responses

I am working on those right now. 😉 

Expect some PRs soon!

**Comment by panicbit** [comment]
Cool! Thanks!

Klemens Schölhorn <notifications@github.com> schrieb am Do., 3. Nov. 2016,
19:29:

**Comment by klemens** [comment]
It turns out, this is a little bit more complicated:

It consistently fails above 1446 byte, which is also what is suggested here: http://wiki.vg/RCON
Between 1434 and 1445 it fails almost always after at most two or three tries.
Between 1414 and 1433 it fails sporadically (at first it fails fast, but takes longer after some "warmup").

So it *seems* like drawing the line at 1413 is fine (at least I did not have a single failed attempt after 10k tests).
